
    vSerie[1].nombre :=  
    vSerie[1].descripcion := 
    vSerie[1].cantTemp := 
    vSerie[1].vTemp[1].anioDeEmision := 
    vSerie[1].vTemp[1].cantEpiDeTemp := 
    vSerie[1].vTemp[1].vVideo[1].titulo := 
    vSerie[1].vTemp[1].vVideo[1].descripcion := 
    vSerie[1].vTemp[1].vVideo[1].duracionEnSegundos := 1320;
    vSerie[1].vTemp[1].vVideo[1].visualizaciones := 0;
    vSerie[1].vTemp[1].vVideo[2].titulo := 
    vSerie[1].vTemp[1].vVideo[2].descripcion := 
    vSerie[1].vTemp[1].vVideo[2].duracionEnSegundos := 1320;
    vSerie[1].vTemp[1].vVideo[2].visualizaciones := 0;
    vSerie[1].vTemp[1].vVideo[3].titulo := 
    vSerie[1].vTemp[1].vVideo[3].descripcion := 
    vSerie[1].vTemp[1].vVideo[3].duracionEnSegundos := 1320;
    vSerie[1].vTemp[1].vVideo[3].visualizaciones := 0;
    vSerie[1].vTemp[1].vVideo[4].titulo := 
    vSerie[1].vTemp[1].vVideo[4].descripcion := 
    vSerie[1].vTemp[1].vVideo[4].duracionEnSegundos := 1320;
    vSerie[1].vTemp[1].vVideo[4].visualizaciones := 0;
    vSerie[1].vTemp[1].vVideo[5].titulo := 
    vSerie[1].vTemp[1].vVideo[5].descripcion := 
    vSerie[1].vTemp[1].vVideo[5].duracionEnSegundos := 1320;
    vSerie[1].vTemp[1].vVideo[5].visualizaciones := 0;
    vSerie[1].vTemp[2].anioDeEmision := 
    vSerie[1].vTemp[2].cantEpiDeTemp := 
    vSerie[1].vTemp[2].vVideo[1].titulo := 
    vSerie[1].vTemp[2].vVideo[1].descripcion := 
    vSerie[1].vTemp[2].vVideo[1].duracionEnSegundos := 1320;
    vSerie[1].vTemp[2].vVideo[1].visualizaciones := 0;
    vSerie[1].vTemp[2].vVideo[2].titulo := 
    vSerie[1].vTemp[2].vVideo[2].descripcion := 
    vSerie[1].vTemp[2].vVideo[2].duracionEnSegundos := 1320;
    vSerie[1].vTemp[2].vVideo[2].visualizaciones := 0;
    vSerie[1].vTemp[2].vVideo[3].titulo := 
    vSerie[1].vTemp[2].vVideo[3].descripcion := 
    vSerie[1].vTemp[2].vVideo[3].duracionEnSegundos := 1320;
    vSerie[1].vTemp[2].vVideo[3].visualizaciones := 0;
    vSerie[1].vTemp[2].vVideo[4].titulo := 
    vSerie[1].vTemp[2].vVideo[4].descripcion := 
    vSerie[1].vTemp[2].vVideo[4].duracionEnSegundos := 1320;
    vSerie[1].vTemp[2].vVideo[4].visualizaciones := 0;
    vSerie[1].vTemp[2].vVideo[5].titulo := 
    vSerie[1].vTemp[2].vVideo[5].descripcion := 
    vSerie[1].vTemp[2].vVideo[5].duracionEnSegundos := 1320;
    vSerie[1].vTemp[2].vVideo[5].visualizaciones := 0;
    vSerie[1].vTemp[3].anioDeEmision := 
    vSerie[1].vTemp[3].cantEpiDeTemp := 
    vSerie[1].vTemp[3].vVideo[1].titulo := 
    vSerie[1].vTemp[3].vVideo[1].descripcion := 
    vSerie[1].vTemp[3].vVideo[1].duracionEnSegundos := 1320;
    vSerie[1].vTemp[3].vVideo[1].visualizaciones := 0;
    vSerie[1].vTemp[3].vVideo[2].titulo := 
    vSerie[1].vTemp[3].vVideo[2].descripcion := 
    vSerie[1].vTemp[3].vVideo[2].duracionEnSegundos := 1320;
    vSerie[1].vTemp[3].vVideo[2].visualizaciones := 0;
    vSerie[1].vTemp[3].vVideo[3].titulo := 
    vSerie[1].vTemp[3].vVideo[3].descripcion := 
    vSerie[1].vTemp[3].vVideo[3].duracionEnSegundos := 1320;
    vSerie[1].vTemp[3].vVideo[3].visualizaciones := 0;
    vSerie[1].vTemp[3].vVideo[4].titulo := 
    vSerie[1].vTemp[3].vVideo[4].descripcion := 
    vSerie[1].vTemp[3].vVideo[4].duracionEnSegundos := 1320;
    vSerie[1].vTemp[3].vVideo[4].visualizaciones := 0;
    vSerie[1].vTemp[3].vVideo[5].titulo := 
    vSerie[1].vTemp[3].vVideo[5].descripcion := 
    vSerie[1].vTemp[3].vVideo[5].duracionEnSegundos := 1320;
    vSerie[1].vTemp[3].vVideo[5].visualizaciones := 0;
    vSerie[1].vTemp[4].anioDeEmision := 
    vSerie[1].vTemp[4].cantEpiDeTemp := 
    vSerie[1].vTemp[4].vVideo[1].titulo := 
    vSerie[1].vTemp[4].vVideo[1].descripcion := 
    vSerie[1].vTemp[4].vVideo[1].duracionEnSegundos := 1320;
    vSerie[1].vTemp[4].vVideo[1].visualizaciones := 0;
    vSerie[1].vTemp[4].vVideo[2].titulo := 
    vSerie[1].vTemp[4].vVideo[2].descripcion := 
    vSerie[1].vTemp[4].vVideo[2].duracionEnSegundos := 1320;
    vSerie[1].vTemp[4].vVideo[2].visualizaciones := 0;
    vSerie[1].vTemp[4].vVideo[3].titulo := 
    vSerie[1].vTemp[4].vVideo[3].descripcion := 
    vSerie[1].vTemp[4].vVideo[3].duracionEnSegundos := 1320;
    vSerie[1].vTemp[4].vVideo[3].visualizaciones := 0;
    vSerie[1].vTemp[4].vVideo[4].titulo := 
    vSerie[1].vTemp[4].vVideo[4].descripcion := 
    vSerie[1].vTemp[4].vVideo[4].duracionEnSegundos := 1320;
    vSerie[1].vTemp[4].vVideo[4].visualizaciones := 0;
    vSerie[1].vTemp[4].vVideo[5].titulo := 
    vSerie[1].vTemp[4].vVideo[5].descripcion := 
    vSerie[1].vTemp[4].vVideo[5].duracionEnSegundos := 1320;
    vSerie[1].vTemp[4].vVideo[5].visualizaciones := 0;
    vSerie[2].nombre :=  
    vSerie[2].descripcion := 
    vSerie[2].cantTemp := 
    vSerie[2].vTemp[1].anioDeEmision := 
    vSerie[2].vTemp[1].cantEpiDeTemp := 
    vSerie[2].vTemp[1].vVideo[1].titulo := 
    vSerie[2].vTemp[1].vVideo[1].descripcion := 
    vSerie[2].vTemp[1].vVideo[1].duracionEnSegundos := 1320;
    vSerie[2].vTemp[1].vVideo[1].visualizaciones := 0;
    vSerie[2].vTemp[1].vVideo[2].titulo := 
    vSerie[2].vTemp[1].vVideo[2].descripcion := 
    vSerie[2].vTemp[1].vVideo[2].duracionEnSegundos := 1320;
    vSerie[2].vTemp[1].vVideo[2].visualizaciones := 0;
    vSerie[2].vTemp[1].vVideo[3].titulo := 
    vSerie[2].vTemp[1].vVideo[3].descripcion := 
    vSerie[2].vTemp[1].vVideo[3].duracionEnSegundos := 1320;
    vSerie[2].vTemp[1].vVideo[3].visualizaciones := 0;
    vSerie[2].vTemp[1].vVideo[4].titulo := 
    vSerie[2].vTemp[1].vVideo[4].descripcion := 
    vSerie[2].vTemp[1].vVideo[4].duracionEnSegundos := 1320;
    vSerie[2].vTemp[1].vVideo[4].visualizaciones := 0;
    vSerie[2].vTemp[1].vVideo[5].titulo := 
    vSerie[2].vTemp[1].vVideo[5].descripcion := 
    vSerie[2].vTemp[1].vVideo[5].duracionEnSegundos := 1320;
    vSerie[2].vTemp[1].vVideo[5].visualizaciones := 0;
    vSerie[2].vTemp[2].anioDeEmision := 
    vSerie[2].vTemp[2].cantEpiDeTemp := 
    vSerie[2].vTemp[2].vVideo[1].titulo := 
    vSerie[2].vTemp[2].vVideo[1].descripcion := 
    vSerie[2].vTemp[2].vVideo[1].duracionEnSegundos := 1320;
    vSerie[2].vTemp[2].vVideo[1].visualizaciones := 0;
    vSerie[2].vTemp[2].vVideo[2].titulo := 
    vSerie[2].vTemp[2].vVideo[2].descripcion := 
    vSerie[2].vTemp[2].vVideo[2].duracionEnSegundos := 1320;
    vSerie[2].vTemp[2].vVideo[2].visualizaciones := 0;
    vSerie[2].vTemp[2].vVideo[3].titulo := 
    vSerie[2].vTemp[2].vVideo[3].descripcion := 
    vSerie[2].vTemp[2].vVideo[3].duracionEnSegundos := 1320;
    vSerie[2].vTemp[2].vVideo[3].visualizaciones := 0;
    vSerie[2].vTemp[2].vVideo[4].titulo := 
    vSerie[2].vTemp[2].vVideo[4].descripcion := 
    vSerie[2].vTemp[2].vVideo[4].duracionEnSegundos := 1320;
    vSerie[2].vTemp[2].vVideo[4].visualizaciones := 0;
    vSerie[2].vTemp[2].vVideo[5].titulo := 
    vSerie[2].vTemp[2].vVideo[5].descripcion := 
    vSerie[2].vTemp[2].vVideo[5].duracionEnSegundos := 1320;
    vSerie[2].vTemp[2].vVideo[5].visualizaciones := 0;
    vSerie[2].vTemp[3].anioDeEmision := 
    vSerie[2].vTemp[3].cantEpiDeTemp := 
    vSerie[2].vTemp[3].vVideo[1].titulo := 
    vSerie[2].vTemp[3].vVideo[1].descripcion := 
    vSerie[2].vTemp[3].vVideo[1].duracionEnSegundos := 1320;
    vSerie[2].vTemp[3].vVideo[1].visualizaciones := 0;
    vSerie[2].vTemp[3].vVideo[2].titulo := 
    vSerie[2].vTemp[3].vVideo[2].descripcion := 
    vSerie[2].vTemp[3].vVideo[2].duracionEnSegundos := 1320;
    vSerie[2].vTemp[3].vVideo[2].visualizaciones := 0;
    vSerie[2].vTemp[3].vVideo[3].titulo := 
    vSerie[2].vTemp[3].vVideo[3].descripcion := 
    vSerie[2].vTemp[3].vVideo[3].duracionEnSegundos := 1320;
    vSerie[2].vTemp[3].vVideo[3].visualizaciones := 0;
    vSerie[2].vTemp[3].vVideo[4].titulo := 
    vSerie[2].vTemp[3].vVideo[4].descripcion := 
    vSerie[2].vTemp[3].vVideo[4].duracionEnSegundos := 1320;
    vSerie[2].vTemp[3].vVideo[4].visualizaciones := 0;
    vSerie[2].vTemp[3].vVideo[5].titulo := 
    vSerie[2].vTemp[3].vVideo[5].descripcion := 
    vSerie[2].vTemp[3].vVideo[5].duracionEnSegundos := 1320;
    vSerie[2].vTemp[3].vVideo[5].visualizaciones := 0;
    vSerie[2].vTemp[4].anioDeEmision := 
    vSerie[2].vTemp[4].cantEpiDeTemp := 
    vSerie[2].vTemp[4].vVideo[1].titulo := 
    vSerie[2].vTemp[4].vVideo[1].descripcion := 
    vSerie[2].vTemp[4].vVideo[1].duracionEnSegundos := 1320;
    vSerie[2].vTemp[4].vVideo[1].visualizaciones := 0;
    vSerie[2].vTemp[4].vVideo[2].titulo := 
    vSerie[2].vTemp[4].vVideo[2].descripcion := 
    vSerie[2].vTemp[4].vVideo[2].duracionEnSegundos := 1320;
    vSerie[2].vTemp[4].vVideo[2].visualizaciones := 0;
    vSerie[2].vTemp[4].vVideo[3].titulo := 
    vSerie[2].vTemp[4].vVideo[3].descripcion := 
    vSerie[2].vTemp[4].vVideo[3].duracionEnSegundos := 1320;
    vSerie[2].vTemp[4].vVideo[3].visualizaciones := 0;
    vSerie[2].vTemp[4].vVideo[4].titulo := 
    vSerie[2].vTemp[4].vVideo[4].descripcion := 
    vSerie[2].vTemp[4].vVideo[4].duracionEnSegundos := 1320;
    vSerie[2].vTemp[4].vVideo[4].visualizaciones := 0;
    vSerie[2].vTemp[4].vVideo[5].titulo := 
    vSerie[2].vTemp[4].vVideo[5].descripcion := 
    vSerie[2].vTemp[4].vVideo[5].duracionEnSegundos := 1320;
    vSerie[2].vTemp[4].vVideo[5].visualizaciones := 0;
    vSerie[3].nombre :=  
    vSerie[3].descripcion := 
    vSerie[3].cantTemp := 
    vSerie[3].vTemp[1].anioDeEmision := 
    vSerie[3].vTemp[1].cantEpiDeTemp := 
    vSerie[3].vTemp[1].vVideo[1].titulo := 
    vSerie[3].vTemp[1].vVideo[1].descripcion := 
    vSerie[3].vTemp[1].vVideo[1].duracionEnSegundos := 1320;
    vSerie[3].vTemp[1].vVideo[1].visualizaciones := 0;
    vSerie[3].vTemp[1].vVideo[2].titulo := 
    vSerie[3].vTemp[1].vVideo[2].descripcion := 
    vSerie[3].vTemp[1].vVideo[2].duracionEnSegundos := 1320;
    vSerie[3].vTemp[1].vVideo[2].visualizaciones := 0;
    vSerie[3].vTemp[1].vVideo[3].titulo := 
    vSerie[3].vTemp[1].vVideo[3].descripcion := 
    vSerie[3].vTemp[1].vVideo[3].duracionEnSegundos := 1320;
    vSerie[3].vTemp[1].vVideo[3].visualizaciones := 0;
    vSerie[3].vTemp[1].vVideo[4].titulo := 
    vSerie[3].vTemp[1].vVideo[4].descripcion := 
    vSerie[3].vTemp[1].vVideo[4].duracionEnSegundos := 1320;
    vSerie[3].vTemp[1].vVideo[4].visualizaciones := 0;
    vSerie[3].vTemp[1].vVideo[5].titulo := 
    vSerie[3].vTemp[1].vVideo[5].descripcion := 
    vSerie[3].vTemp[1].vVideo[5].duracionEnSegundos := 1320;
    vSerie[3].vTemp[1].vVideo[5].visualizaciones := 0;
    vSerie[3].vTemp[2].anioDeEmision := 
    vSerie[3].vTemp[2].cantEpiDeTemp := 
    vSerie[3].vTemp[2].vVideo[1].titulo := 
    vSerie[3].vTemp[2].vVideo[1].descripcion := 
    vSerie[3].vTemp[2].vVideo[1].duracionEnSegundos := 1320;
    vSerie[3].vTemp[2].vVideo[1].visualizaciones := 0;
    vSerie[3].vTemp[2].vVideo[2].titulo := 
    vSerie[3].vTemp[2].vVideo[2].descripcion := 
    vSerie[3].vTemp[2].vVideo[2].duracionEnSegundos := 1320;
    vSerie[3].vTemp[2].vVideo[2].visualizaciones := 0;
    vSerie[3].vTemp[2].vVideo[3].titulo := 
    vSerie[3].vTemp[2].vVideo[3].descripcion := 
    vSerie[3].vTemp[2].vVideo[3].duracionEnSegundos := 1320;
    vSerie[3].vTemp[2].vVideo[3].visualizaciones := 0;
    vSerie[3].vTemp[2].vVideo[4].titulo := 
    vSerie[3].vTemp[2].vVideo[4].descripcion := 
    vSerie[3].vTemp[2].vVideo[4].duracionEnSegundos := 1320;
    vSerie[3].vTemp[2].vVideo[4].visualizaciones := 0;
    vSerie[3].vTemp[2].vVideo[5].titulo := 
    vSerie[3].vTemp[2].vVideo[5].descripcion := 
    vSerie[3].vTemp[2].vVideo[5].duracionEnSegundos := 1320;
    vSerie[3].vTemp[2].vVideo[5].visualizaciones := 0;
    vSerie[3].vTemp[3].anioDeEmision := 
    vSerie[3].vTemp[3].cantEpiDeTemp := 
    vSerie[3].vTemp[3].vVideo[1].titulo := 
    vSerie[3].vTemp[3].vVideo[1].descripcion := 
    vSerie[3].vTemp[3].vVideo[1].duracionEnSegundos := 1320;
    vSerie[3].vTemp[3].vVideo[1].visualizaciones := 0;
    vSerie[3].vTemp[3].vVideo[2].titulo := 
    vSerie[3].vTemp[3].vVideo[2].descripcion := 
    vSerie[3].vTemp[3].vVideo[2].duracionEnSegundos := 1320;
    vSerie[3].vTemp[3].vVideo[2].visualizaciones := 0;
    vSerie[3].vTemp[3].vVideo[3].titulo := 
    vSerie[3].vTemp[3].vVideo[3].descripcion := 
    vSerie[3].vTemp[3].vVideo[3].duracionEnSegundos := 1320;
    vSerie[3].vTemp[3].vVideo[3].visualizaciones := 0;
    vSerie[3].vTemp[3].vVideo[4].titulo := 
    vSerie[3].vTemp[3].vVideo[4].descripcion := 
    vSerie[3].vTemp[3].vVideo[4].duracionEnSegundos := 1320;
    vSerie[3].vTemp[3].vVideo[4].visualizaciones := 0;
    vSerie[3].vTemp[3].vVideo[5].titulo := 
    vSerie[3].vTemp[3].vVideo[5].descripcion := 
    vSerie[3].vTemp[3].vVideo[5].duracionEnSegundos := 1320;
    vSerie[3].vTemp[3].vVideo[5].visualizaciones := 0;
    vSerie[3].vTemp[4].anioDeEmision := 
    vSerie[3].vTemp[4].cantEpiDeTemp := 
    vSerie[3].vTemp[4].vVideo[1].titulo := 
    vSerie[3].vTemp[4].vVideo[1].descripcion := 
    vSerie[3].vTemp[4].vVideo[1].duracionEnSegundos := 1320;
    vSerie[3].vTemp[4].vVideo[1].visualizaciones := 0;
    vSerie[3].vTemp[4].vVideo[2].titulo := 
    vSerie[3].vTemp[4].vVideo[2].descripcion := 
    vSerie[3].vTemp[4].vVideo[2].duracionEnSegundos := 1320;
    vSerie[3].vTemp[4].vVideo[2].visualizaciones := 0;
    vSerie[3].vTemp[4].vVideo[3].titulo := 
    vSerie[3].vTemp[4].vVideo[3].descripcion := 
    vSerie[3].vTemp[4].vVideo[3].duracionEnSegundos := 1320;
    vSerie[3].vTemp[4].vVideo[3].visualizaciones := 0;
    vSerie[3].vTemp[4].vVideo[4].titulo := 
    vSerie[3].vTemp[4].vVideo[4].descripcion := 
    vSerie[3].vTemp[4].vVideo[4].duracionEnSegundos := 1320;
    vSerie[3].vTemp[4].vVideo[4].visualizaciones := 0;
    vSerie[3].vTemp[4].vVideo[5].titulo := 
    vSerie[3].vTemp[4].vVideo[5].descripcion := 
    vSerie[3].vTemp[4].vVideo[5].duracionEnSegundos := 1320;
    vSerie[3].vTemp[4].vVideo[5].visualizaciones := 0;
    vSerie[4].nombre :=  
    vSerie[4].descripcion := 
    vSerie[4].cantTemp := 
    vSerie[4].vTemp[1].anioDeEmision := 
    vSerie[4].vTemp[1].cantEpiDeTemp := 
    vSerie[4].vTemp[1].vVideo[1].titulo := 
    vSerie[4].vTemp[1].vVideo[1].descripcion := 
    vSerie[4].vTemp[1].vVideo[1].duracionEnSegundos := 1320;
    vSerie[4].vTemp[1].vVideo[1].visualizaciones := 0;
    vSerie[4].vTemp[1].vVideo[2].titulo := 
    vSerie[4].vTemp[1].vVideo[2].descripcion := 
    vSerie[4].vTemp[1].vVideo[2].duracionEnSegundos := 1320;
    vSerie[4].vTemp[1].vVideo[2].visualizaciones := 0;
    vSerie[4].vTemp[1].vVideo[3].titulo := 
    vSerie[4].vTemp[1].vVideo[3].descripcion := 
    vSerie[4].vTemp[1].vVideo[3].duracionEnSegundos := 1320;
    vSerie[4].vTemp[1].vVideo[3].visualizaciones := 0;
    vSerie[4].vTemp[1].vVideo[4].titulo := 
    vSerie[4].vTemp[1].vVideo[4].descripcion := 
    vSerie[4].vTemp[1].vVideo[4].duracionEnSegundos := 1320;
    vSerie[4].vTemp[1].vVideo[4].visualizaciones := 0;
    vSerie[4].vTemp[1].vVideo[5].titulo := 
    vSerie[4].vTemp[1].vVideo[5].descripcion := 
    vSerie[4].vTemp[1].vVideo[5].duracionEnSegundos := 1320;
    vSerie[4].vTemp[1].vVideo[5].visualizaciones := 0;
    vSerie[4].vTemp[2].anioDeEmision := 
    vSerie[4].vTemp[2].cantEpiDeTemp := 
    vSerie[4].vTemp[2].vVideo[1].titulo := 
    vSerie[4].vTemp[2].vVideo[1].descripcion := 
    vSerie[4].vTemp[2].vVideo[1].duracionEnSegundos := 1320;
    vSerie[4].vTemp[2].vVideo[1].visualizaciones := 0;
    vSerie[4].vTemp[2].vVideo[2].titulo := 
    vSerie[4].vTemp[2].vVideo[2].descripcion := 
    vSerie[4].vTemp[2].vVideo[2].duracionEnSegundos := 1320;
    vSerie[4].vTemp[2].vVideo[2].visualizaciones := 0;
    vSerie[4].vTemp[2].vVideo[3].titulo := 
    vSerie[4].vTemp[2].vVideo[3].descripcion := 
    vSerie[4].vTemp[2].vVideo[3].duracionEnSegundos := 1320;
    vSerie[4].vTemp[2].vVideo[3].visualizaciones := 0;
    vSerie[4].vTemp[2].vVideo[4].titulo := 
    vSerie[4].vTemp[2].vVideo[4].descripcion := 
    vSerie[4].vTemp[2].vVideo[4].duracionEnSegundos := 1320;
    vSerie[4].vTemp[2].vVideo[4].visualizaciones := 0;
    vSerie[4].vTemp[2].vVideo[5].titulo := 
    vSerie[4].vTemp[2].vVideo[5].descripcion := 
    vSerie[4].vTemp[2].vVideo[5].duracionEnSegundos := 1320;
    vSerie[4].vTemp[2].vVideo[5].visualizaciones := 0;
    vSerie[4].vTemp[3].anioDeEmision := 
    vSerie[4].vTemp[3].cantEpiDeTemp := 
    vSerie[4].vTemp[3].vVideo[1].titulo := 
    vSerie[4].vTemp[3].vVideo[1].descripcion := 
    vSerie[4].vTemp[3].vVideo[1].duracionEnSegundos := 1320;
    vSerie[4].vTemp[3].vVideo[1].visualizaciones := 0;
    vSerie[4].vTemp[3].vVideo[2].titulo := 
    vSerie[4].vTemp[3].vVideo[2].descripcion := 
    vSerie[4].vTemp[3].vVideo[2].duracionEnSegundos := 1320;
    vSerie[4].vTemp[3].vVideo[2].visualizaciones := 0;
    vSerie[4].vTemp[3].vVideo[3].titulo := 
    vSerie[4].vTemp[3].vVideo[3].descripcion := 
    vSerie[4].vTemp[3].vVideo[3].duracionEnSegundos := 1320;
    vSerie[4].vTemp[3].vVideo[3].visualizaciones := 0;
    vSerie[4].vTemp[3].vVideo[4].titulo := 
    vSerie[4].vTemp[3].vVideo[4].descripcion := 
    vSerie[4].vTemp[3].vVideo[4].duracionEnSegundos := 1320;
    vSerie[4].vTemp[3].vVideo[4].visualizaciones := 0;
    vSerie[4].vTemp[3].vVideo[5].titulo := 
    vSerie[4].vTemp[3].vVideo[5].descripcion := 
    vSerie[4].vTemp[3].vVideo[5].duracionEnSegundos := 1320;
    vSerie[4].vTemp[3].vVideo[5].visualizaciones := 0;
    vSerie[4].vTemp[4].anioDeEmision := 
    vSerie[4].vTemp[4].cantEpiDeTemp := 
    vSerie[4].vTemp[4].vVideo[1].titulo := 
    vSerie[4].vTemp[4].vVideo[1].descripcion := 
    vSerie[4].vTemp[4].vVideo[1].duracionEnSegundos := 1320;
    vSerie[4].vTemp[4].vVideo[1].visualizaciones := 0;
    vSerie[4].vTemp[4].vVideo[2].titulo := 
    vSerie[4].vTemp[4].vVideo[2].descripcion := 
    vSerie[4].vTemp[4].vVideo[2].duracionEnSegundos := 1320;
    vSerie[4].vTemp[4].vVideo[2].visualizaciones := 0;
    vSerie[4].vTemp[4].vVideo[3].titulo := 
    vSerie[4].vTemp[4].vVideo[3].descripcion := 
    vSerie[4].vTemp[4].vVideo[3].duracionEnSegundos := 1320;
    vSerie[4].vTemp[4].vVideo[3].visualizaciones := 0;
    vSerie[4].vTemp[4].vVideo[4].titulo := 
    vSerie[4].vTemp[4].vVideo[4].descripcion := 
    vSerie[4].vTemp[4].vVideo[4].duracionEnSegundos := 1320;
    vSerie[4].vTemp[4].vVideo[4].visualizaciones := 0;
    vSerie[4].vTemp[4].vVideo[5].titulo := 
    vSerie[4].vTemp[4].vVideo[5].descripcion := 
    vSerie[4].vTemp[4].vVideo[5].duracionEnSegundos := 1320;
    vSerie[4].vTemp[4].vVideo[5].visualizaciones := 0;
