unit unit2;

interface

procedure cargarSeries(var vSerie: tvSerie);


implementation

procedure cargarSeries(var vSerie: tvSerie);
    {Pre: Se recibe el vector Series vacio o con datos
    * Post: Se devuelve el vector con las series cargadas y eliminando los datos anteriores en
    * caso de haberlo tenido}
begin
    vSerie[1].nombre := 'Friends';
    vSerie[1].descripcion := 'Friends fue una serie de televisión estadounidense creada y producida por Marta Kauffman y David Crane.'
    vSerie[1].cantTemp :=  10;
    vSerie[1].vTemp[1].anioDeEmision := '1994';
    vSerie[1].vTemp[1].cantEpiDeTemp := 24;
    vSerie[1].vTemp[1].vVideo[1].titulo := 'En el que Monica tiene una nueva compañera';
    vSerie[1].vTemp[1].vVideo[1].descripcion := 'S01E01 Friends'
    vSerie[1].vTemp[1].vVideo[1].duracionEnSegundos := 1320;
    vSerie[1].vTemp[1].vVideo[1].visualizaciones := 0;
    vSerie[1].vTemp[1].vVideo[2].titulo := 'El de la ecografía al final';
    vSerie[1].vTemp[1].vVideo[2].descripcion := 'S01E02 Friends';
    vSerie[1].vTemp[1].vVideo[2].duracionEnSegundos := 1320;
    vSerie[1].vTemp[1].vVideo[2].visualizaciones := 0;
    vSerie[1].vTemp[1].vVideo[3].titulo := 'El del pulgar'
    vSerie[1].vTemp[1].vVideo[3].descripcion := 'S01E03 Friends';
    vSerie[1].vTemp[1].vVideo[3].duracionEnSegundos := 1320;
    vSerie[1].vTemp[1].vVideo[3].visualizaciones := 0;
    vSerie[1].vTemp[1].vVideo[4].titulo := 'El de George Stephanopoulos';
    vSerie[1].vTemp[1].vVideo[4].descripcion := 'S01E04 Friends'
    vSerie[1].vTemp[1].vVideo[4].duracionEnSegundos := 1320;
    vSerie[1].vTemp[1].vVideo[4].visualizaciones := 0;
    vSerie[1].vTemp[1].vVideo[5].titulo := 'El del detergente germano oriental extrafuerte ';
    vSerie[1].vTemp[1].vVideo[5].descripcion := 'S01E05 Friends';
    vSerie[1].vTemp[1].vVideo[5].duracionEnSegundos := 1320;
    vSerie[1].vTemp[1].vVideo[5].visualizaciones := 0;
    vSerie[1].vTemp[2].anioDeEmision := 1995;
    vSerie[1].vTemp[2].cantEpiDeTemp := 5;
    vSerie[1].vTemp[2].vVideo[1].titulo := 'El de la nueva novia de Ross';
    vSerie[1].vTemp[2].vVideo[1].descripcion := 'S02E01 Friends';
    vSerie[1].vTemp[2].vVideo[1].duracionEnSegundos := 1320;
    vSerie[1].vTemp[2].vVideo[1].visualizaciones := 0;
    vSerie[1].vTemp[2].vVideo[2].titulo := 'El de la leche materna '
    vSerie[1].vTemp[2].vVideo[2].descripcion := 'S02E02 Friends'
    vSerie[1].vTemp[2].vVideo[2].duracionEnSegundos := 1320;
    vSerie[1].vTemp[2].vVideo[2].visualizaciones := 0;
    vSerie[1].vTemp[2].vVideo[3].titulo := 'En el que Heckles muere'
    vSerie[1].vTemp[2].vVideo[3].descripcion := 'S02E03 Friends'
    vSerie[1].vTemp[2].vVideo[3].duracionEnSegundos := 1320;
    vSerie[1].vTemp[2].vVideo[3].visualizaciones := 0;
    vSerie[1].vTemp[2].vVideo[4].titulo := 'El del marido de Phoebe'
    vSerie[1].vTemp[2].vVideo[4].descripcion := 'S02E04 Friends'
    vSerie[1].vTemp[2].vVideo[4].duracionEnSegundos := 1320;
    vSerie[1].vTemp[2].vVideo[4].visualizaciones := 0;
    vSerie[1].vTemp[2].vVideo[5].titulo := 'El de los cinco filetes y la berenjena '
    vSerie[1].vTemp[2].vVideo[5].descripcion := 'S02E05 Friends'
    vSerie[1].vTemp[2].vVideo[5].duracionEnSegundos := 1320;
    vSerie[1].vTemp[2].vVideo[5].visualizaciones := 0;
    vSerie[1].vTemp[3].anioDeEmision := 
    vSerie[1].vTemp[3].cantEpiDeTemp := 
    vSerie[1].vTemp[3].vVideo[1].titulo := 
    vSerie[1].vTemp[3].vVideo[1].descripcion := 
    vSerie[1].vTemp[3].vVideo[1].duracionEnSegundos := 1320;
    vSerie[1].vTemp[3].vVideo[1].visualizaciones := 0;
    vSerie[1].vTemp[3].vVideo[2].titulo := 
    vSerie[1].vTemp[3].vVideo[2].descripcion := 
    vSerie[1].vTemp[3].vVideo[2].duracionEnSegundos := 1320;
    vSerie[1].vTemp[3].vVideo[2].visualizaciones := 0;
    vSerie[1].vTemp[3].vVideo[3].titulo := 
    vSerie[1].vTemp[3].vVideo[3].descripcion := 
    vSerie[1].vTemp[3].vVideo[3].duracionEnSegundos := 1320;
    vSerie[1].vTemp[3].vVideo[3].visualizaciones := 0;
    vSerie[1].vTemp[3].vVideo[4].titulo := 
    vSerie[1].vTemp[3].vVideo[4].descripcion := 
    vSerie[1].vTemp[3].vVideo[4].duracionEnSegundos := 1320;
    vSerie[1].vTemp[3].vVideo[4].visualizaciones := 0;
    vSerie[1].vTemp[3].vVideo[5].titulo := 
    vSerie[1].vTemp[3].vVideo[5].descripcion := 
    vSerie[1].vTemp[3].vVideo[5].duracionEnSegundos := 1320;
    vSerie[1].vTemp[3].vVideo[5].visualizaciones := 0;
    vSerie[1].vTemp[4].anioDeEmision := 
    vSerie[1].vTemp[4].cantEpiDeTemp := 
    vSerie[1].vTemp[4].vVideo[1].titulo := 
    vSerie[1].vTemp[4].vVideo[1].descripcion := 
    vSerie[1].vTemp[4].vVideo[1].duracionEnSegundos := 1320;
    vSerie[1].vTemp[4].vVideo[1].visualizaciones := 0;
    vSerie[1].vTemp[4].vVideo[2].titulo := 
    vSerie[1].vTemp[4].vVideo[2].descripcion := 
    vSerie[1].vTemp[4].vVideo[2].duracionEnSegundos := 1320;
    vSerie[1].vTemp[4].vVideo[2].visualizaciones := 0;
    vSerie[1].vTemp[4].vVideo[3].titulo := 
    vSerie[1].vTemp[4].vVideo[3].descripcion := 
    vSerie[1].vTemp[4].vVideo[3].duracionEnSegundos := 1320;
    vSerie[1].vTemp[4].vVideo[3].visualizaciones := 0;
    vSerie[1].vTemp[4].vVideo[4].titulo := 
    vSerie[1].vTemp[4].vVideo[4].descripcion := 
    vSerie[1].vTemp[4].vVideo[4].duracionEnSegundos := 1320;
    vSerie[1].vTemp[4].vVideo[4].visualizaciones := 0;
    vSerie[1].vTemp[4].vVideo[5].titulo := 
    vSerie[1].vTemp[4].vVideo[5].descripcion := 
    vSerie[1].vTemp[4].vVideo[5].duracionEnSegundos := 1320;
    vSerie[1].vTemp[4].vVideo[5].visualizaciones := 0;
    vSerie[2].nombre :=  
    vSerie[2].descripcion := 
    vSerie[2].cantTemp := 
    vSerie[2].vTemp[1].anioDeEmision := 
    vSerie[2].vTemp[1].cantEpiDeTemp := 
    vSerie[2].vTemp[1].vVideo[1].titulo := 
    vSerie[2].vTemp[1].vVideo[1].descripcion := 
    vSerie[2].vTemp[1].vVideo[1].duracionEnSegundos := 1320;
    vSerie[2].vTemp[1].vVideo[1].visualizaciones := 0;
    vSerie[2].vTemp[1].vVideo[2].titulo := 
    vSerie[2].vTemp[1].vVideo[2].descripcion := 
    vSerie[2].vTemp[1].vVideo[2].duracionEnSegundos := 1320;
    vSerie[2].vTemp[1].vVideo[2].visualizaciones := 0;
    vSerie[2].vTemp[1].vVideo[3].titulo := 
    vSerie[2].vTemp[1].vVideo[3].descripcion := 
    vSerie[2].vTemp[1].vVideo[3].duracionEnSegundos := 1320;
    vSerie[2].vTemp[1].vVideo[3].visualizaciones := 0;
    vSerie[2].vTemp[1].vVideo[4].titulo := 
    vSerie[2].vTemp[1].vVideo[4].descripcion := 
    vSerie[2].vTemp[1].vVideo[4].duracionEnSegundos := 1320;
    vSerie[2].vTemp[1].vVideo[4].visualizaciones := 0;
    vSerie[2].vTemp[1].vVideo[5].titulo := 
    vSerie[2].vTemp[1].vVideo[5].descripcion := 
    vSerie[2].vTemp[1].vVideo[5].duracionEnSegundos := 1320;
    vSerie[2].vTemp[1].vVideo[5].visualizaciones := 0;
    vSerie[2].vTemp[2].anioDeEmision := 
    vSerie[2].vTemp[2].cantEpiDeTemp := 
    vSerie[2].vTemp[2].vVideo[1].titulo := 
    vSerie[2].vTemp[2].vVideo[1].descripcion := 
    vSerie[2].vTemp[2].vVideo[1].duracionEnSegundos := 1320;
    vSerie[2].vTemp[2].vVideo[1].visualizaciones := 0;
    vSerie[2].vTemp[2].vVideo[2].titulo := 
    vSerie[2].vTemp[2].vVideo[2].descripcion := 
    vSerie[2].vTemp[2].vVideo[2].duracionEnSegundos := 1320;
    vSerie[2].vTemp[2].vVideo[2].visualizaciones := 0;
    vSerie[2].vTemp[2].vVideo[3].titulo := 
    vSerie[2].vTemp[2].vVideo[3].descripcion := 
    vSerie[2].vTemp[2].vVideo[3].duracionEnSegundos := 1320;
    vSerie[2].vTemp[2].vVideo[3].visualizaciones := 0;
    vSerie[2].vTemp[2].vVideo[4].titulo := 
    vSerie[2].vTemp[2].vVideo[4].descripcion := 
    vSerie[2].vTemp[2].vVideo[4].duracionEnSegundos := 1320;
    vSerie[2].vTemp[2].vVideo[4].visualizaciones := 0;
    vSerie[2].vTemp[2].vVideo[5].titulo := 
    vSerie[2].vTemp[2].vVideo[5].descripcion := 
    vSerie[2].vTemp[2].vVideo[5].duracionEnSegundos := 1320;
    vSerie[2].vTemp[2].vVideo[5].visualizaciones := 0;
    vSerie[2].vTemp[3].anioDeEmision := 
    vSerie[2].vTemp[3].cantEpiDeTemp := 
    vSerie[2].vTemp[3].vVideo[1].titulo := 
    vSerie[2].vTemp[3].vVideo[1].descripcion := 
    vSerie[2].vTemp[3].vVideo[1].duracionEnSegundos := 1320;
    vSerie[2].vTemp[3].vVideo[1].visualizaciones := 0;
    vSerie[2].vTemp[3].vVideo[2].titulo := 
    vSerie[2].vTemp[3].vVideo[2].descripcion := 
    vSerie[2].vTemp[3].vVideo[2].duracionEnSegundos := 1320;
    vSerie[2].vTemp[3].vVideo[2].visualizaciones := 0;
    vSerie[2].vTemp[3].vVideo[3].titulo := 
    vSerie[2].vTemp[3].vVideo[3].descripcion := 
    vSerie[2].vTemp[3].vVideo[3].duracionEnSegundos := 1320;
    vSerie[2].vTemp[3].vVideo[3].visualizaciones := 0;
    vSerie[2].vTemp[3].vVideo[4].titulo := 
    vSerie[2].vTemp[3].vVideo[4].descripcion := 
    vSerie[2].vTemp[3].vVideo[4].duracionEnSegundos := 1320;
    vSerie[2].vTemp[3].vVideo[4].visualizaciones := 0;
    vSerie[2].vTemp[3].vVideo[5].titulo := 
    vSerie[2].vTemp[3].vVideo[5].descripcion := 
    vSerie[2].vTemp[3].vVideo[5].duracionEnSegundos := 1320;
    vSerie[2].vTemp[3].vVideo[5].visualizaciones := 0;
    vSerie[2].vTemp[4].anioDeEmision := 
    vSerie[2].vTemp[4].cantEpiDeTemp := 
    vSerie[2].vTemp[4].vVideo[1].titulo := 
    vSerie[2].vTemp[4].vVideo[1].descripcion := 
    vSerie[2].vTemp[4].vVideo[1].duracionEnSegundos := 1320;
    vSerie[2].vTemp[4].vVideo[1].visualizaciones := 0;
    vSerie[2].vTemp[4].vVideo[2].titulo := 
    vSerie[2].vTemp[4].vVideo[2].descripcion := 
    vSerie[2].vTemp[4].vVideo[2].duracionEnSegundos := 1320;
    vSerie[2].vTemp[4].vVideo[2].visualizaciones := 0;
    vSerie[2].vTemp[4].vVideo[3].titulo := 
    vSerie[2].vTemp[4].vVideo[3].descripcion := 
    vSerie[2].vTemp[4].vVideo[3].duracionEnSegundos := 1320;
    vSerie[2].vTemp[4].vVideo[3].visualizaciones := 0;
    vSerie[2].vTemp[4].vVideo[4].titulo := 
    vSerie[2].vTemp[4].vVideo[4].descripcion := 
    vSerie[2].vTemp[4].vVideo[4].duracionEnSegundos := 1320;
    vSerie[2].vTemp[4].vVideo[4].visualizaciones := 0;
    vSerie[2].vTemp[4].vVideo[5].titulo := 
    vSerie[2].vTemp[4].vVideo[5].descripcion := 
    vSerie[2].vTemp[4].vVideo[5].duracionEnSegundos := 1320;
    vSerie[2].vTemp[4].vVideo[5].visualizaciones := 0;
    vSerie[3].nombre :=  
    vSerie[3].descripcion := 
    vSerie[3].cantTemp := 
    vSerie[3].vTemp[1].anioDeEmision := 
    vSerie[3].vTemp[1].cantEpiDeTemp := 
    vSerie[3].vTemp[1].vVideo[1].titulo := 
    vSerie[3].vTemp[1].vVideo[1].descripcion := 
    vSerie[3].vTemp[1].vVideo[1].duracionEnSegundos := 1320;
    vSerie[3].vTemp[1].vVideo[1].visualizaciones := 0;
    vSerie[3].vTemp[1].vVideo[2].titulo := 
    vSerie[3].vTemp[1].vVideo[2].descripcion := 
    vSerie[3].vTemp[1].vVideo[2].duracionEnSegundos := 1320;
    vSerie[3].vTemp[1].vVideo[2].visualizaciones := 0;
    vSerie[3].vTemp[1].vVideo[3].titulo := 
    vSerie[3].vTemp[1].vVideo[3].descripcion := 
    vSerie[3].vTemp[1].vVideo[3].duracionEnSegundos := 1320;
    vSerie[3].vTemp[1].vVideo[3].visualizaciones := 0;
    vSerie[3].vTemp[1].vVideo[4].titulo := 
    vSerie[3].vTemp[1].vVideo[4].descripcion := 
    vSerie[3].vTemp[1].vVideo[4].duracionEnSegundos := 1320;
    vSerie[3].vTemp[1].vVideo[4].visualizaciones := 0;
    vSerie[3].vTemp[1].vVideo[5].titulo := 
    vSerie[3].vTemp[1].vVideo[5].descripcion := 
    vSerie[3].vTemp[1].vVideo[5].duracionEnSegundos := 1320;
    vSerie[3].vTemp[1].vVideo[5].visualizaciones := 0;
    vSerie[3].vTemp[2].anioDeEmision := 
    vSerie[3].vTemp[2].cantEpiDeTemp := 
    vSerie[3].vTemp[2].vVideo[1].titulo := 
    vSerie[3].vTemp[2].vVideo[1].descripcion := 
    vSerie[3].vTemp[2].vVideo[1].duracionEnSegundos := 1320;
    vSerie[3].vTemp[2].vVideo[1].visualizaciones := 0;
    vSerie[3].vTemp[2].vVideo[2].titulo := 
    vSerie[3].vTemp[2].vVideo[2].descripcion := 
    vSerie[3].vTemp[2].vVideo[2].duracionEnSegundos := 1320;
    vSerie[3].vTemp[2].vVideo[2].visualizaciones := 0;
    vSerie[3].vTemp[2].vVideo[3].titulo := 
    vSerie[3].vTemp[2].vVideo[3].descripcion := 
    vSerie[3].vTemp[2].vVideo[3].duracionEnSegundos := 1320;
    vSerie[3].vTemp[2].vVideo[3].visualizaciones := 0;
    vSerie[3].vTemp[2].vVideo[4].titulo := 
    vSerie[3].vTemp[2].vVideo[4].descripcion := 
    vSerie[3].vTemp[2].vVideo[4].duracionEnSegundos := 1320;
    vSerie[3].vTemp[2].vVideo[4].visualizaciones := 0;
    vSerie[3].vTemp[2].vVideo[5].titulo := 
    vSerie[3].vTemp[2].vVideo[5].descripcion := 
    vSerie[3].vTemp[2].vVideo[5].duracionEnSegundos := 1320;
    vSerie[3].vTemp[2].vVideo[5].visualizaciones := 0;
    vSerie[3].vTemp[3].anioDeEmision := 
    vSerie[3].vTemp[3].cantEpiDeTemp := 
    vSerie[3].vTemp[3].vVideo[1].titulo := 
    vSerie[3].vTemp[3].vVideo[1].descripcion := 
    vSerie[3].vTemp[3].vVideo[1].duracionEnSegundos := 1320;
    vSerie[3].vTemp[3].vVideo[1].visualizaciones := 0;
    vSerie[3].vTemp[3].vVideo[2].titulo := 
    vSerie[3].vTemp[3].vVideo[2].descripcion := 
    vSerie[3].vTemp[3].vVideo[2].duracionEnSegundos := 1320;
    vSerie[3].vTemp[3].vVideo[2].visualizaciones := 0;
    vSerie[3].vTemp[3].vVideo[3].titulo := 
    vSerie[3].vTemp[3].vVideo[3].descripcion := 
    vSerie[3].vTemp[3].vVideo[3].duracionEnSegundos := 1320;
    vSerie[3].vTemp[3].vVideo[3].visualizaciones := 0;
    vSerie[3].vTemp[3].vVideo[4].titulo := 
    vSerie[3].vTemp[3].vVideo[4].descripcion := 
    vSerie[3].vTemp[3].vVideo[4].duracionEnSegundos := 1320;
    vSerie[3].vTemp[3].vVideo[4].visualizaciones := 0;
    vSerie[3].vTemp[3].vVideo[5].titulo := 
    vSerie[3].vTemp[3].vVideo[5].descripcion := 
    vSerie[3].vTemp[3].vVideo[5].duracionEnSegundos := 1320;
    vSerie[3].vTemp[3].vVideo[5].visualizaciones := 0;
    vSerie[3].vTemp[4].anioDeEmision := 
    vSerie[3].vTemp[4].cantEpiDeTemp := 
    vSerie[3].vTemp[4].vVideo[1].titulo := 
    vSerie[3].vTemp[4].vVideo[1].descripcion := 
    vSerie[3].vTemp[4].vVideo[1].duracionEnSegundos := 1320;
    vSerie[3].vTemp[4].vVideo[1].visualizaciones := 0;
    vSerie[3].vTemp[4].vVideo[2].titulo := 
    vSerie[3].vTemp[4].vVideo[2].descripcion := 
    vSerie[3].vTemp[4].vVideo[2].duracionEnSegundos := 1320;
    vSerie[3].vTemp[4].vVideo[2].visualizaciones := 0;
    vSerie[3].vTemp[4].vVideo[3].titulo := 
    vSerie[3].vTemp[4].vVideo[3].descripcion := 
    vSerie[3].vTemp[4].vVideo[3].duracionEnSegundos := 1320;
    vSerie[3].vTemp[4].vVideo[3].visualizaciones := 0;
    vSerie[3].vTemp[4].vVideo[4].titulo := 
    vSerie[3].vTemp[4].vVideo[4].descripcion := 
    vSerie[3].vTemp[4].vVideo[4].duracionEnSegundos := 1320;
    vSerie[3].vTemp[4].vVideo[4].visualizaciones := 0;
    vSerie[3].vTemp[4].vVideo[5].titulo := 
    vSerie[3].vTemp[4].vVideo[5].descripcion := 
    vSerie[3].vTemp[4].vVideo[5].duracionEnSegundos := 1320;
    vSerie[3].vTemp[4].vVideo[5].visualizaciones := 0;
    vSerie[4].nombre :=  
    vSerie[4].descripcion := 
    vSerie[4].cantTemp := 
    vSerie[4].vTemp[1].anioDeEmision := 
    vSerie[4].vTemp[1].cantEpiDeTemp := 
    vSerie[4].vTemp[1].vVideo[1].titulo := 
    vSerie[4].vTemp[1].vVideo[1].descripcion := 
    vSerie[4].vTemp[1].vVideo[1].duracionEnSegundos := 1320;
    vSerie[4].vTemp[1].vVideo[1].visualizaciones := 0;
    vSerie[4].vTemp[1].vVideo[2].titulo := 
    vSerie[4].vTemp[1].vVideo[2].descripcion := 
    vSerie[4].vTemp[1].vVideo[2].duracionEnSegundos := 1320;
    vSerie[4].vTemp[1].vVideo[2].visualizaciones := 0;
    vSerie[4].vTemp[1].vVideo[3].titulo := 
    vSerie[4].vTemp[1].vVideo[3].descripcion := 
    vSerie[4].vTemp[1].vVideo[3].duracionEnSegundos := 1320;
    vSerie[4].vTemp[1].vVideo[3].visualizaciones := 0;
    vSerie[4].vTemp[1].vVideo[4].titulo := 
    vSerie[4].vTemp[1].vVideo[4].descripcion := 
    vSerie[4].vTemp[1].vVideo[4].duracionEnSegundos := 1320;
    vSerie[4].vTemp[1].vVideo[4].visualizaciones := 0;
    vSerie[4].vTemp[1].vVideo[5].titulo := 
    vSerie[4].vTemp[1].vVideo[5].descripcion := 
    vSerie[4].vTemp[1].vVideo[5].duracionEnSegundos := 1320;
    vSerie[4].vTemp[1].vVideo[5].visualizaciones := 0;
    vSerie[4].vTemp[2].anioDeEmision := 
    vSerie[4].vTemp[2].cantEpiDeTemp := 
    vSerie[4].vTemp[2].vVideo[1].titulo := 
    vSerie[4].vTemp[2].vVideo[1].descripcion := 
    vSerie[4].vTemp[2].vVideo[1].duracionEnSegundos := 1320;
    vSerie[4].vTemp[2].vVideo[1].visualizaciones := 0;
    vSerie[4].vTemp[2].vVideo[2].titulo := 
    vSerie[4].vTemp[2].vVideo[2].descripcion := 
    vSerie[4].vTemp[2].vVideo[2].duracionEnSegundos := 1320;
    vSerie[4].vTemp[2].vVideo[2].visualizaciones := 0;
    vSerie[4].vTemp[2].vVideo[3].titulo := 
    vSerie[4].vTemp[2].vVideo[3].descripcion := 
    vSerie[4].vTemp[2].vVideo[3].duracionEnSegundos := 1320;
    vSerie[4].vTemp[2].vVideo[3].visualizaciones := 0;
    vSerie[4].vTemp[2].vVideo[4].titulo := 
    vSerie[4].vTemp[2].vVideo[4].descripcion := 
    vSerie[4].vTemp[2].vVideo[4].duracionEnSegundos := 1320;
    vSerie[4].vTemp[2].vVideo[4].visualizaciones := 0;
    vSerie[4].vTemp[2].vVideo[5].titulo := 
    vSerie[4].vTemp[2].vVideo[5].descripcion := 
    vSerie[4].vTemp[2].vVideo[5].duracionEnSegundos := 1320;
    vSerie[4].vTemp[2].vVideo[5].visualizaciones := 0;
    vSerie[4].vTemp[3].anioDeEmision := 
    vSerie[4].vTemp[3].cantEpiDeTemp := 
    vSerie[4].vTemp[3].vVideo[1].titulo := 
    vSerie[4].vTemp[3].vVideo[1].descripcion := 
    vSerie[4].vTemp[3].vVideo[1].duracionEnSegundos := 1320;
    vSerie[4].vTemp[3].vVideo[1].visualizaciones := 0;
    vSerie[4].vTemp[3].vVideo[2].titulo := 
    vSerie[4].vTemp[3].vVideo[2].descripcion := 
    vSerie[4].vTemp[3].vVideo[2].duracionEnSegundos := 1320;
    vSerie[4].vTemp[3].vVideo[2].visualizaciones := 0;
    vSerie[4].vTemp[3].vVideo[3].titulo := 
    vSerie[4].vTemp[3].vVideo[3].descripcion := 
    vSerie[4].vTemp[3].vVideo[3].duracionEnSegundos := 1320;
    vSerie[4].vTemp[3].vVideo[3].visualizaciones := 0;
    vSerie[4].vTemp[3].vVideo[4].titulo := 
    vSerie[4].vTemp[3].vVideo[4].descripcion := 
    vSerie[4].vTemp[3].vVideo[4].duracionEnSegundos := 1320;
    vSerie[4].vTemp[3].vVideo[4].visualizaciones := 0;
    vSerie[4].vTemp[3].vVideo[5].titulo := 
    vSerie[4].vTemp[3].vVideo[5].descripcion := 
    vSerie[4].vTemp[3].vVideo[5].duracionEnSegundos := 1320;
    vSerie[4].vTemp[3].vVideo[5].visualizaciones := 0;
    vSerie[4].vTemp[4].anioDeEmision := 
    vSerie[4].vTemp[4].cantEpiDeTemp := 
    vSerie[4].vTemp[4].vVideo[1].titulo := 
    vSerie[4].vTemp[4].vVideo[1].descripcion := 
    vSerie[4].vTemp[4].vVideo[1].duracionEnSegundos := 1320;
    vSerie[4].vTemp[4].vVideo[1].visualizaciones := 0;
    vSerie[4].vTemp[4].vVideo[2].titulo := 
    vSerie[4].vTemp[4].vVideo[2].descripcion := 
    vSerie[4].vTemp[4].vVideo[2].duracionEnSegundos := 1320;
    vSerie[4].vTemp[4].vVideo[2].visualizaciones := 0;
    vSerie[4].vTemp[4].vVideo[3].titulo := 
    vSerie[4].vTemp[4].vVideo[3].descripcion := 
    vSerie[4].vTemp[4].vVideo[3].duracionEnSegundos := 1320;
    vSerie[4].vTemp[4].vVideo[3].visualizaciones := 0;
    vSerie[4].vTemp[4].vVideo[4].titulo := 
    vSerie[4].vTemp[4].vVideo[4].descripcion := 
    vSerie[4].vTemp[4].vVideo[4].duracionEnSegundos := 1320;
    vSerie[4].vTemp[4].vVideo[4].visualizaciones := 0;
    vSerie[4].vTemp[4].vVideo[5].titulo := 
    vSerie[4].vTemp[4].vVideo[5].descripcion := 
    vSerie[4].vTemp[4].vVideo[5].duracionEnSegundos := 1320;
    vSerie[4].vTemp[4].vVideo[5].visualizaciones := 0;




begin 
end.
